services:

  website:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    platform: linux/arm64
    container_name: jamelclyons
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ${PACKAGES_DIR}:/app/packages
    environment:
      CHOKIDAR_USEPOLLING: "true"
      RUNNING_IN_DOCKER: "true"
    networks:
      - j.c.lyons_enterprises
      - seven_tech
      - orb

networks:
  j.c.lyons_enterprises:
    name: j.c.lyons_enterprises
    external: true
  seven_tech:
    name: seven_tech
    external: true
  orb:
    name: orb
    external: true
