FROM node:22

ARG AUTH_TOKEN
ENV AUTH_TOKEN=$AUTH_TOKEN

RUN test -n "$AUTH_TOKEN" || (echo "Token is NOT set" && exit 1)

WORKDIR /app

COPY .npmrc .npmrc

COPY ./scss ./scss

COPY ./src ./src

COPY ./.firebaserc .

COPY ./firebase.json .

COPY ./index.html .

COPY ./package.json .

COPY ./skills.json .

COPY ./styles.css .

COPY tsconfig.json .

COPY ./user.json .

COPY ./vite.config.ts .

RUN npm install

RUN rm -f .npmrc

RUN npm run build

EXPOSE 5002

CMD ["npm", "run", "stage"]