name: portfolio

services:

  staging-website:
    env_file: .env
    hostname: ${URL}
    build:
      context: .
      dockerfile: Dockerfile.staging
      args:
        AUTH_TOKEN: ${AUTH_TOKEN}
    platform: linux/arm64
    container_name: portfolio-staging
    image: jamelclyons/portfolio:staging
    restart: unless-stopped
    volumes:
      - ./package-lock.json:/app/package-lock.json
    ports:
      - "5002:5002"
    environment:
      NODE_ENV: production
      CHOKIDAR_USEPOLLING: "true"
      RUNNING_IN_DOCKER: "true"
    networks:
      - j.c.lyons_enterprises
      - seven_tech
      - orb

networks:
  j.c.lyons_enterprises:
    name: j.c.lyons_enterprises
    external: true
  seven_tech:
    name: seven_tech
    external: true
  orb:
    name: orb
    external: true
