services:

  website:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AUTH_TOKEN: ${AUTH_TOKEN}
    platform: linux/arm64
    container_name: portfolio
    image: jamelclyons/portfolio:latest
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      NODE_ENV: production
      CHOKIDAR_USEPOLLING: "true"
      RUNNING_IN_DOCKER: "true"
    networks:
      - j.c.lyons_enterprises
      - seven_tech
      - orb

networks:
  j.c.lyons_enterprises:
    name: j.c.lyons_enterprises
    external: true
  seven_tech:
    name: seven_tech
    external: true
  orb:
    name: orb
    external: true
