FROM node:22-alpine AS build

ARG AUTH_TOKEN
ENV AUTH_TOKEN=$AUTH_TOKEN
ARG VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_APP_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
ARG VITE_FIREBASE_MEASUREMENT_ID
ENV VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID
ARG VITE_GITHUB_TOKEN
ENV VITE_GITHUB_TOKEN=$VITE_GITHUB_TOKEN
ARG VITE_GITLAB_TOKEN
ENV VITE_GITLAB_TOKEN=$VITE_GITLAB_TOKEN
ARG VITE_GITLAB_API
ENV VITE_GITLAB_API=$VITE_GITLAB_API

WORKDIR /app

COPY ./src ./src

COPY .firebaserc .

COPY .npmrc .npmrc

COPY ./contacts.json .

COPY ./firebase.json .

COPY ./index.html .

COPY ./organizations.json .

COPY ./package-lock.json .

COPY ./package.json .

COPY ./skills.json .

COPY ./styles.css .

COPY ./tsconfig.json .

COPY ./user.json .

COPY ./vite-env.d.ts .

COPY ./vite.config.ts .

RUN npm ci

RUN npm run build

RUN rm -rf .npmrc

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]