name: dev-portfolio

services:

  dev-website:
    platform: linux/arm64
    container_name: dev-jamelclyons
    env_file: .env

    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "3000:3000"
    volumes:
      - ..:/app:cached
      - /app/node_modules
      - ${PACKAGES_DIR}:/app/Packages
    environment:
      CHOKIDAR_USEPOLLING: "true"
      RUNNING_IN_DOCKER: "true"
      DEBUG: true          
      NODE_ENV: development
    networks:
      - j.c.lyons_enterprises
      - seven_tech
      - orb

networks:
  j.c.lyons_enterprises:
    name: j.c.lyons_enterprises
    external: true
  seven_tech:
    name: seven_tech
    external: true
  orb:
    name: orb
    external: true
